apiVersion: v1
kind: Service
metadata:
  name: server2
  labels:
    app: server2
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: server2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servers2
  labels:
    app: server2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server2
  template:
    metadata:
      labels:
        app: server2
    spec:
      containers:
      - name: server1
        image: container-all-the-things_server2:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
